openapi: 3.0.2
info:
  title: Credenciamento Pessoa Física
  version: "1"

security:
 - basicAuth: []

tags:
 - name: Cadastro Pessoa Física
   description: Cadastrar o portador de conta Pessoa Física 

servers: [
    {
      "url": "https://api-beta.zoop.ws",
      "description": "Produção"
    },
    {
      "url": "https://apigw-sandbox.zoop.ws/v2",
      "description": "Sandbox"
    }    
    ]
    
paths:
  "/marketplaces/{marketplaceId}/banking/accreditation/holders":
    post:
      tags:
        - Cadastro Pessoa Física
      operationId: create_1
      parameters:
        - name: marketplaceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HolderRequestObject'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HolderResponseHolder'
            text/plain:
              schema:
                $ref: '#/components/schemas/HolderResponseHolder'


components:
  securitySchemes:
     basicAuth:
       type: http
       scheme: basic  
  schemas:
    HolderResponseHolder:
      type: object
      properties:
        id:
          type: string
          example: "85b006901d034e18a235bd995b0d6352"
        name:
          type: string
          example: "João Silva"
        revenue:
          type: number
          format: double
          example: 5500.50
        email:
          type: string
          example: "joao.silva@gmail.com"
        status:
          type: string
          example: waiting_info_and_documents
        marketplace_id:
          type: string
          example: "f8c2bfb884e4486c8e0eee15be5c3ab1"
        marketplace_name:
          type: string
          example: "Marketplace Integração Testes Banking"
        created_at:
          type: string
          example: "2020-11-05T11:35:32.038494"
        updated_at:
          type: string
          example: "2020-11-05T11:35:32.038497"
        type:
          type: string
          example: individual
        nationalRegistration:
          type: string
          example: "10057698007"
        birthday:
          type: string
          example: "1982-12-15"
        mothers_name:
          type: string
          example: "Maria da Silva"
        identity_card:
          type: string
          example: "156032898"
        pep:
          type: string
          example: "false"
        cbo:
          type: string
          example: "252505"
        _links:
          $ref: '#/components/schemas/Links'

    HolderRequestObject:
      required:
        - cbo
        - email
        - name
        - revenue
        - type
        - mothers_name
        - national_registration
      type: object
      properties:
        cbo:
          type: string
          description: Código de ocupação do portador da conta. Valor disponível em Listar CBO
          example: "252505"
        type:
          type: string
          enum:
            - individual
            - business
          description: Tipo do portador da conta. Para um holder pessoa física o valor deve ser sempre individual 
        pep:
          type: boolean
          default: false
          description: Declaração se o portador da conta é uma pessoa exposta politicamente. 
        identity_card:
          type: string
          description: RG do portador da conta 
          example: 156032898
        mothers_name:
          type: string
          description: Nome da mãe do portador da conta 
          example: "Maria Silva"
        birthday:
          type: string
          description: Data de nascimento do portador da conta.
          example: "1982-12-15" 
        revenue:
          type: number
          description: Renda média do portador da conta
          format: double
          example: "5500.00" 
        national_registration:
          type: string
          description: CPF do portador da conta.
          example: "10057698007" 
        email:
          type: string
          description: email do portador da conta.
          example: "joao.silva@gmail.com" 
        name:
          type: string
          description: Nome completo do portador da conta.
          example: "João da Silva" 

    Links:
      type: object
      $ref: '#/components/schemas/Link'

    Link:
      type: object
      properties:
        self:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352"
            
            type: 
              type: string
              example: "GET"
        phones:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/phones"
            type: 
              type: string
              example: "GET"
        adresses:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/addresses"
            type: 
              type: string
              example: "GET"        
        documents:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/documents"
            type: 
              type: string
              example: "GET"
