openapi: 3.0.2
info:
  title: Credenciamento Pessoa Física
  version: "1"

security:
 - basicAuth: []

tags:
 - name: Criação de contas
   description: Credenciamento e criação de contas 

servers: [
    {
      "url": "https://api-beta.zoop.ws",
      "description": "Produção"
    },
    {
      "url": "https://apigw-sandbox.zoop.ws",
      "description": "Sandbox"
    }    
    ]
    
paths:
  "/v2/marketplaces/{marketplace_id}/banking/accreditation/holders":
    post:
      summary: Cadastro portador pessoa física
      tags:
        - Credenciamento
      parameters:
        - $ref: "#/components/parameters/marketplaceID"
      requestBody:
        content:
          application/json:
            schema:
              oneOf: 
                - $ref: '#/components/schemas/IndividualHolderRequest'
                - $ref: '#/components/schemas/BusinessHolderRequest'
                
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/IndividualHolderResponse'
                  - $ref: '#/components/schemas/BusinessHolderResponse'
  "/v2/marketplaces/{marketplace_id}/banking/accreditation/holders/{holder_id}":
    put:
      summary: Alterar portador pessoa física
      tags:
        - Credenciamento
      parameters:
        - $ref: "#/components/parameters/marketplaceID"
        - $ref: "#/components/parameters/holderID"
      requestBody:
        content:
          application/json:
            schema:
              OneOf:
                - $ref: '#/components/schemas/IndividualHolderRequestPut'
                - $ref: '#/components/schemas/BusinessHolderRequestPut'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/IndividualHolderResponse'
                  - $ref: '#/components/schemas/BusinessHolderResponse'


components:
  securitySchemes:
     basicAuth:
       type: http
       scheme: basic 
  parameters:
      marketplaceID:
        name: marketplace_id
        in: path
        description: ID do marketplace
        required: true
        schema:
          type: string
      holderID:
        name: holder_id
        in: path
        description: ID do holder (dono da conta)
        required: true
        schema:
          type: string

  schemas:
    IndividualHolderResponse:
      type: object
      properties:
        id:
          type: string
          example: "85b006901d034e18a235bd995b0d6352"
        name:
          type: string
          example: "João Silva"
        revenue:
          type: number
          format: double
          example: 5500.50
        email:
          type: string
          example: "joao.silva@gmail.com"
        status:
          type: string
          example: waiting_info_and_documents
        marketplace_id:
          type: string
          example: "f8c2bfb884e4486c8e0eee15be5c3ab1"
        marketplace_name:
          type: string
          example: "Marketplace Integração Testes Banking"
        created_at:
          type: string
          example: "2020-11-05T11:35:32.038494"
        updated_at:
          type: string
          example: "2020-11-05T11:35:32.038497"
        type:
          type: string
          example: individual
        nationalRegistration:
          type: string
          example: "10057698007"
        birthday:
          type: string
          example: "1982-12-15"
        mothers_name:
          type: string
          example: "Maria da Silva"
        identity_card:
          type: string
          example: "156032898"
        pep:
          type: string
          example: "false"
        cbo:
          type: string
          example: "252505"
        _links:
          $ref: '#/components/schemas/Links'
    BusinessHolderResponse:
      type: object
      properties:
        id:
          type: string
          example: "85b006901d034e18a235bd995b0d6352"
        name:
          type: string
          example: "João Silva"
        revenue:
          type: number
          format: double
          example: 5500.50
        email:
          type: string
          example: "joao.silva@gmail.com"
        status:
          type: string
          example: waiting_info_and_documents
        marketplace_id:
          type: string
          example: "f8c2bfb884e4486c8e0eee15be5c3ab1"
        marketplace_name:
          type: string
          example: "Marketplace Integração Testes Banking"
        created_at:
          type: string
          example: "2020-11-05T11:35:32.038494"
        updated_at:
          type: string
          example: "2020-11-05T11:35:32.038497"
        type:
          type: string
          example: individual
        nationalRegistration:
          type: string
          example: "10057698007"
        birthday:
          type: string
          example: "1982-12-15"
        mothers_name:
          type: string
          example: "Maria da Silva"
        identity_card:
          type: string
          example: "156032898"
        pep:
          type: string
          example: "false"
        cbo:
          type: string
          example: "252505"
        cnae:
          type: string
          description: Código de classificação nacional de atividades econômicas
          example: "0111301"
        legal_name:
          type: string
          description: Razão social da empresa (somente tipo business)
          example: "Teste Comercio de Alimentos Ltda." 
        establishment:
          type: object
          properties:
            format: 
              type: string
              example: "LTDA"
            date:
              type: string
              example: "2001-03-05"     
        _links:
           $ref: '#/components/schemas/Links'
    IndividualHolderRequest:
      required:
        - cbo
        - email
        - name
        - revenue
        - type
        - mothers_name
        - national_registration
      type: object
      properties:
        type:
          type: string
          example: "individual"
          description: Tipo do portador da conta. Para um holder pessoa física o valor deve ser sempre individual 
        name:
          type: string
          description: Nome completo do portador da conta.
          example: "João da Silva" 
        email:
          type: string
          description: email do portador da conta.
          example: "joao.silva@gmail.com" 
        birthday:
          type: string
          description: Data de nascimento do portador da conta.
          example: "1982-12-15" 
        identity_card:
          type: string
          description: RG do portador da conta (Somente para type "individual") 
          example: 156032898
        national_registration:
          type: string
          description: CPF do portador da conta.
          example: "10057698007" 
        cbo:
          type: string
          description: Código de ocupação do portador da conta. Valor disponível em Listar CBO (Somente para type "individual")
          example: "252505"
        pep:
          type: boolean
          default: false
          description: Declaração se o portador da conta é uma pessoa exposta politicamente. 
        mothers_name:
          type: string
          description: Nome da mãe do portador da conta 
          example: "Maria Silva"
        revenue:
          type: number
          description: Renda média do portador (tipo individual) da conta ou receita média da empresa (tipo business) 
          format: double
          example: "5500.00" 
    BusinessHolderRequest:
      required:
        - cbo
        - email
        - name
        - revenue
        - type
        - mothers_name
        - national_registration
      type: object
      properties:
        type:
          type: string
          example: business
          description: Tipo do portador da conta. Para um holder pessoa física o valor deve ser sempre individual 
        name:
          type: string
          description: Nome completo do portador da conta.
          example: "João da Silva" 
        email:
          type: string
          description: email do portador da conta.
          example: "joao.silva@gmail.com" 
        birthday:
          type: string
          description: Data de nascimento do portador da conta.
          example: "1982-12-15" 
        identity_card:
          type: string
          description: RG do portador da conta (Somente para type "individual") 
          example: 156032898
        national_registration:
          type: string
          description: CPF do portador da conta.
          example: "10057698007" 
        cbo:
          type: string
          description: Código de ocupação do portador da conta. Valor disponível em Listar CBO (Somente para type "individual")
          example: "252505"
        pep:
          type: boolean
          default: false
          description: Declaração se o portador da conta é uma pessoa exposta politicamente. 
        mothers_name:
          type: string
          description: Nome da mãe do portador da conta 
          example: "Maria Silva"
        revenue:
          type: number
          description: Renda média do portador (tipo individual) da conta ou receita média da empresa (tipo business) 
          format: double
          example: "5500.00" 
        cnae:
          type: string
          description: Código de classificação nacional de atividades econômicas
          example: "0111301"
        legal_name:
          type: string
          description: Razão social da empresa (somente tipo business)
          example: "Teste Comercio de Alimentos Ltda." 
        establishment:
          type: object
          properties:
            format: 
              type: string
              description: "Formato de constituição da empresa. Valores possíveis: SS (Sociedade Simples), SC (Sociedade Cooperativa), SPE (Sociedade de Propósito Especifico), LTDA (Sociedade Limitada), SA (Sociedade por Ações), ME (Micro empresa) , MEI (Microempreendedor individual), EI (Empresário individual), EIRELI (Empresário Individual de Responsabilidade Limitada) , SNC (Sociedade em Nome Coletivo), SCS (Sociedade em Comandita Simples), SCA (Sociedade em Comandita por Ações (somente tipo business)"
              example: "LTDA"
            date:
              type: string
              description: Data de constituição da empresa (somente tipo business)
              example: "2001-03-05"     
 
    IndividualHolderRequestPut:
      type: object
      properties:
        birthday:
          type: string
          description: Data de nascimento do portador da conta.
          example: "1982-12-15" 
        cbo:
          type: string
          description: Código de ocupação do portador da conta. Valor disponível em Listar CBO
          example: "252505"
        mothers_name:
          type: string
          description: Nome da mãe do portador da conta 
          example: "Maria Silva"
        revenue:
          type: number
          description: Renda média do portador da conta
          format: double
          example: "5500.00" 
    BusinessHolderRequestPut:
      type: object
      properties:
        mothers_name:
          type: string
          description: Nome da mãe do portador da conta 
          example: "Maria Silva"
        revenue:
          type: number
          description: Renda média do portador da conta
          format: double
          example: "5500.00" 
        cnae:
          type: string
          description: Código de classificação nacional de atividades econômicas
          example: "0111301"
        establishment:
          type: object
          properties:
            date:
              type: string
              description: Data de constituição da empresa (somente tipo business)
              example: "2001-03-05"     

    Links:
      type: object
      $ref: '#/components/schemas/Link'

    Link:
      type: object
      properties:
        self:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352"
            
            type: 
              type: string
              example: "GET"
        phones:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/phones"
            type: 
              type: string
              example: "GET"
        adresses:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/addresses"
            type: 
              type: string
              example: "GET"        
        documents:
          type: object
          properties: 
            href: 
              type: string
              example: "https://apigw-sandbox.zoop.ws/v2/marketplaces/f8c2bfb884e4486c8e0eee15be5c3ab1/banking/accreditation/holders/85b006901d034e18a235bd995b0d6352/documents"
            type: 
              type: string
              example: "GET"
